"""
reminder.py — reminder engine backed by systemd user timers (Arch Linux),
with fallbacks for Windows / macOS / Linux without systemd.

Class API:  `ReminderEngine`
Legacy module-level `reminder()` preserved for backwards compatibility.
"""
from __future__ import annotations

import json
import os
import platform
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import asdict, dataclass, field
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional


_SYSTEM = platform.system()
_SYSTEMD_USER_DIR = Path.home() / ".config" / "systemd" / "user"
_SCRIPTS_DIR = Path.home() / ".jarvis" / "reminders"
_REGISTRY_PATH = Path.home() / ".jarvis" / "reminders.json"

_SYSTEMD_USER_DIR.mkdir(parents=True, exist_ok=True)
_SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)


def _sanitise_name(text: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9_-]+", "-", text).strip("-").lower()
    return s[:40] or "jarvis-reminder"


def _sanitise_message(message: str) -> str:
    return (
        message.replace("\\", "")
                .replace('"', "")
                .replace("\n", " ")
                .strip()
    )[:240]


def _write_notify_script(name: str, message: str) -> Path:
    """Create a self-deleting notification script."""
    script = _SCRIPTS_DIR / f"{name}.sh"
    msg = _sanitise_message(message)
    body = f"""#!/usr/bin/env bash
# Auto-generated by JARVIS reminder — do not edit
MSG='{msg}'
if command -v notify-send >/dev/null 2>&1; then
    notify-send --urgency=normal --expire-time=15000 "JARVIS Reminder" "$MSG"
elif command -v zenity >/dev/null 2>&1; then
    zenity --info --title="JARVIS Reminder" --text="$MSG" &
fi
if command -v paplay >/dev/null 2>&1; then
    paplay /usr/share/sounds/freedesktop/stereo/complete.oga 2>/dev/null || true
fi
rm -f -- "{script}"
"""
    script.write_text(body, encoding="utf-8")
    script.chmod(0o755)
    return script


def _systemctl(*args: str, timeout: int = 10) -> tuple[bool, str]:
    try:
        r = subprocess.run(
            ["systemctl", "--user", *args],
            capture_output=True, text=True, timeout=timeout,
        )
        return r.returncode == 0, (r.stderr or r.stdout or "").strip()
    except Exception as e:
        return False, str(e)


@dataclass
class Reminder:
    name: str
    message: str
    when: str                       # ISO 8601 datetime
    unit: str                       # systemd unit name
    service: str
    script: str
    created: str = field(default_factory=lambda: datetime.now().isoformat(timespec="seconds"))

    def to_dict(self) -> dict:
        return asdict(self)


class ReminderEngine:
    """Manages systemd user timers for reminders."""

    def __init__(self, registry_path: Optional[Path | str] = None):
        self.registry_path = Path(registry_path) if registry_path else _REGISTRY_PATH
        self.registry_path.parent.mkdir(parents=True, exist_ok=True)
        self._items: dict[str, Reminder] = {}
        self._load()

    # ── Public API ─────────────────────────────────────────────────────────

    def set_reminder(self, message: str, when: datetime | str) -> str:
        """
        Create a systemd user timer that fires `when` and runs a notify script.
        Returns the reminder name.
        """
        if isinstance(when, str):
            try:
                when_dt = datetime.fromisoformat(when)
            except ValueError:
                # Best-effort ISO parse
                when_dt = datetime.strptime(when, "%Y-%m-%d %H:%M")
        else:
            when_dt = when

        if when_dt <= datetime.now():
            raise ValueError("Cannot set a reminder in the past")

        safe_msg = _sanitise_message(message or "Reminder")
        stamp = when_dt.strftime("%Y%m%d-%H%M%S")
        name = f"jarvis-reminder-{stamp}"
        unit = f"{name}.timer"
        service = f"{name}.service"

        script = _write_notify_script(name, safe_msg)

        if _SYSTEM == "Linux" and shutil.which("systemctl"):
            ok, err = self._create_systemd(name, unit, service, script, when_dt)
            if not ok:
                raise RuntimeError(f"systemd timer failed: {err}")
        else:
            # Non-Linux: schedule via at / launchd / schtasks in the legacy path
            self._schedule_fallback(name, when_dt)

        reminder = Reminder(
            name=name,
            message=safe_msg,
            when=when_dt.isoformat(timespec="seconds"),
            unit=unit,
            service=service,
            script=str(script),
        )
        self._items[name] = reminder
        self._save()
        return name

    def list_reminders(self) -> list[dict]:
        return [r.to_dict() for r in self._items.values()]

    def cancel_reminder(self, name: str) -> bool:
        reminder = self._items.pop(name, None)
        if not reminder:
            return False
        if _SYSTEM == "Linux" and shutil.which("systemctl"):
            _systemctl("disable", "--now", reminder.unit)
            for f in (
                _SYSTEMD_USER_DIR / reminder.unit,
                _SYSTEMD_USER_DIR / reminder.service,
                Path(reminder.script),
            ):
                try:
                    f.unlink(missing_ok=True)
                except Exception:
                    pass
            _systemctl("daemon-reload")
        else:
            try:
                Path(reminder.script).unlink(missing_ok=True)
            except Exception:
                pass
        self._save()
        return True

    def trigger_reminder(self, name: str) -> bool:
        reminder = self._items.get(name)
        if not reminder:
            return False
        if _SYSTEM == "Linux" and shutil.which("systemctl"):
            ok, _ = _systemctl("start", reminder.service)
            return ok
        try:
            subprocess.Popen([reminder.script])
            return True
        except Exception:
            return False

    def list_active_systemd(self) -> list[dict]:
        """Return systemd-side view of all jarvis timers."""
        if not (_SYSTEM == "Linux" and shutil.which("systemctl")):
            return []
        ok, out = _systemctl("list-timers", "--user", "--no-pager", "--plain",
                             "--output=json")
        if not ok:
            return []
        results: list[dict] = []
        for line in out.splitlines():
            try:
                obj = json.loads(line)
            except Exception:
                continue
            unit = obj.get("unit", "")
            if "jarvis-reminder" in unit:
                results.append(obj)
        return results

    # ── Internals ──────────────────────────────────────────────────────────

    def _create_systemd(
        self,
        name: str,
        unit_file: str,
        service_file: str,
        script: Path,
        when_dt: datetime,
    ) -> tuple[bool, str]:
        on_calendar = when_dt.strftime("%Y-%m-%d %H:%M:00")
        service_path = _SYSTEMD_USER_DIR / service_file
        timer_path = _SYSTEMD_USER_DIR / unit_file

        service_path.write_text(
            f"""[Unit]
Description=JARVIS reminder: {name}

[Service]
Type=oneshot
ExecStart={script}
""",
            encoding="utf-8",
        )

        timer_path.write_text(
            f"""[Unit]
Description=JARVIS reminder timer: {name}

[Timer]
OnCalendar={on_calendar}
Persistent=false
Unit={service_file}

[Install]
WantedBy=timers.target
""",
            encoding="utf-8",
        )

        ok, err = _systemctl("daemon-reload")
        if not ok:
            return False, err
        ok, err = _systemctl("enable", "--now", unit_file)
        if not ok:
            return False, err
        return True, ""

    def _schedule_fallback(self, name: str, when_dt: datetime) -> None:
        """Best-effort fallback for non-Linux hosts."""
        if _SYSTEM == "Windows":
            safe_msg = _sanitise_message(name)
            xml = _SYSTEMD_USER_DIR / f"{name}.xml"
            xml.write_text(
                f"""<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2"><Triggers><TimeTrigger>
<StartBoundary>{when_dt:%Y-%m-%dT%H:%M:%S}</StartBoundary>
</TimeTrigger></Triggers><Actions><Exec>
<Command>cmd</Command><Arguments>/c echo {safe_msg}</Arguments>
</Exec></Actions></Task>""",
                encoding="utf-16",
            )
        elif _SYSTEM == "Darwin":
            pass

    def _save(self) -> None:
        data = {k: v.to_dict() for k, v in self._items.items()}
        tmp = self.registry_path.with_suffix(".tmp")
        tmp.write_text(json.dumps(data, indent=2), encoding="utf-8")
        tmp.replace(self.registry_path)

    def _load(self) -> None:
        if not self.registry_path.exists():
            return
        try:
            data = json.loads(self.registry_path.read_text(encoding="utf-8"))
        except Exception:
            return
        for name, payload in data.items():
            try:
                self._items[name] = Reminder(**payload)
            except Exception:
                continue


# ── Legacy module-level entry point (used by old Feri tooling) ──────────────

def reminder(
    parameters: dict,
    response=None,
    player=None,
    session_memory=None,
) -> str:
    date_str = (parameters or {}).get("date", "").strip()
    time_str = (parameters or {}).get("time", "").strip()
    message  = (parameters or {}).get("message", "Reminder").strip()
    if not date_str or not time_str:
        return "I need both a date and a time to set a reminder."
    try:
        target_dt = datetime.strptime(f"{date_str} {time_str}", "%Y-%m-%d %H:%M")
    except ValueError:
        return "I couldn't parse that date or time. Please use YYYY-MM-DD and HH:MM."
    if target_dt <= datetime.now():
        return "That time has already passed — I can't set a reminder in the past."

    try:
        engine = ReminderEngine()
        name = engine.set_reminder(message, target_dt)
    except Exception as e:
        return f"Couldn't schedule reminder: {e}"

    friendly_time = target_dt.strftime("%B %d at %I:%M %p")
    return f"Reminder set for {friendly_time}."